export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_LOGOUT = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CURRENCY_LOADING = 'CURRENCY_LOADING';
export const CURRENCY_LOADED = 'CURRENCY_LOADED';
